spring:
  application:
    name: artify
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "Ov23liulnx30ly9dunB4"
            client-secret: "57aa9771f2424ec8ce237f0d8f7ff8ae8fcecafd"
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
  datasource:
    url: jdbc:mysql://localhost:3306/artify?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: gudtns0924
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: "THIS_IS_A_VERY_STRONG_SECRET_KEY_1234567890!@#$%^&*"